### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by protonichash** [cyberboysumanjay/APIs#5]
Your api's are not responding, why added it if they are not working ???
![Screenshot from 2021-05-19 04-31-22](https://user-images.githubusercontent.com/61425970/118734055-32474b80-b85b-11eb-9811-d2191dc82d2f.png)

**Comment by cyberboysumanjay** [comment]
Hi @protonichash,
The API is working fine for me
![Screenshot_20210519-091341279 (1)](https://user-images.githubusercontent.com/12748990/118753421-9a5d5800-b882-11eb-813a-1066ae19624f.jpg)

Also, if you read the README completely I've already mentioned that it can stop anytime because of several factors.

I try my best to maintain them in my free time but I DO NOT Guarantee it's uptime.

Hope you understand 🙂
