### ISSUE TITLE
Torrent Search api is down

### ISSUE THREAD

**Issue by irlamplex** [cyberboysumanjay/APIs#6]
please could you fix the torrent search api?

**Comment by herbertizidro** [comment]
or open the source code so we can help

**Comment by cyberboysumanjay** [comment]
It seems the IP of the server on which I've deployed the code is blocked. 
I've deployed the code on new Azure Server. It should work fine now. 

Making the code open source will increase the load on the sources and can be blocked easily. That's why I decided to keep it closed source for now.

Closing this issue for now as the API is UP! 🎊

**Comment by herbertizidro** [comment]
Thanks!
    Em sexta-feira, 10 de setembro de 2021 05:25:39 BRT, Sumanjay ***@***.***> escreveu:  
 
 


Closed #6.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
